name: Back

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BACK_SOLUTION_PATH: Back/TutorProject.Searcher/TutorProject.Searcher.sln
  
jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore $BACK_SOLUTION_PATH
      - name: Build
        run: dotnet build $BACK_SOLUTION_PATH --no-restore
      - name: Test
        run: dotnet test $BACK_SOLUTION_PATH --no-build --verbosity normal
